name = "quick-docs-basic"
license = "MIT"
description = "A very basic theme for a quickstart template"
homepage = ""
tags = []
features = []
min_version = "0.101.0"

[author]
  name = "nikclin99"
  homepage = "https://gitee.com/wfell"
