baseURL: /
languageCode: cn
copyright: 'MIT Licensed | Copyright © 2022-present Nick Lin'
defaultContentLanguage: cn
disableHugoGeneratorInject: true

module:
  proxy: https://proxy.golang.com.cn,direct
  imports:
  - path: github.com/nicklin99/quick-docs-basic